### ISSUE TITLE
Templates don't show up in Xcode's new project dialog

### ISSUE THREAD

**Issue by m4tbat** [robrix/Project-Templates#4]
[Possibly a silly question, it's the first time I'm trying to add custom templates to Xcode]

Are the templates supposed to show up in Xcode's new project dialog?

I put the template directory in ~/Library/Developer/Xcode/Templates/Project Templates/ but when I run Xcode and select New project, none of your templates is shown in the dialog.

If I add the templates from https://github.com/borealkiss/Minimal-Template instead, a 'Minimal Template' group appears in the new project dialog with two templates in it.

I'm using Xcode 6.3.

Thanks!

**Comment by robrix** [comment]
Nah, not silly at all. These override Apple’s default templates, so e.g. for the framework template, this is the one you want:

![screen shot 2015-04-21 at 21 24 00](https://cloud.githubusercontent.com/assets/59671/7265741/c349585a-e86c-11e4-8585-939bfa1ae0ec.png)

Gonna close this out, but feel free to comment/open an issue if there’s any trouble!

**Comment by m4tbat** [comment]
Ah, I got it. Thank you!
